name: 雷神加速器自动停止加速脚本

on:
  push:
  schedule:
   # 定时任务，北京时间2点执行任务 2:00（北京时间）-8:00 = -17:00(24进制)cron指定的是格林尼治时间（UTC），如果需要换算成北京时间，要在该cron的基础上增加八小时得到北京时间
   - cron: '17 16 * * *' # UTC时间13:46-13:59对应北京时间21:46-21:59
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: "雷神加速器暂停脚本"
        run: |
          node main.js
        env:
          LEISHEN_USERNAME: ${{ secrets.LEISHEN_USERNAME }}
          LEISHEN_PASSWORD: ${{ secrets.LEISHEN_PASSWORD }}
